# program settings
ompThreads: 1
rngSeed: 1234
# simulation box
simBoxLow: [100.0,100.0,100.0]
simBoxHigh: [100.0,100.0,100.0]
simBoxPBC: [false,false,true]
wallLowZ: false
wallHighZ: false
# initialization box
initBoxLow: [20.0,20.0,20.0]
initBoxHigh: [80.0,80.0,80.0]
# initialization inside a circle 
initCircularCrossSection: [false,false,false]
# components < -1  or > 1 will be randomly set
initOrient: [1,0,0]
# physical settings 
viscosity: 0.001   #pN/(um^2.s)
KBT: 0.00411       #pN.um, 300K
# Sylinder
sylinderNumber: 100
sylinderLength: 1.0
sylinderLengthSigma: -1.0
sylinderDiameter: 0.024
# timestepping
dt: 0.001 # s
timeTotal: 1.0 # s
timeSnap: 0.1 # s
# CollisionSolver
colResTol: 0.00001 # 1e-5 format may be incompatible
colMaxIte: 8000
colNewtonRefine: false



