# program settings
rngSeed: 1234
# simulation box
simBoxLow: [0.0, 0.0, 0.0]
simBoxHigh: [25.0, 25.0, 25.0]
simBoxPBC: [false, false, false]
wallLowZ: true
wallHighZ: true
# initialization box
initBoxLow: [5.0, 5.0, 0.0]
initBoxHigh: [20.0, 20.0, 25.0]
# initialization inside a circle
initCircularX: false
# components < -1  or > 1 will be randomly set
initOrient: [2, 2, 2]
# physical settings
viscosity: 0.01 #pN/(um^2.s)
KBT: 0.00411 #pN.um, 300K
# Sylinder
sylinderFixed: false
sylinderNumber: 400
sylinderLength: 3.0
sylinderLengthColRatio: 1.0
sylinderLengthSigma: -1.0
sylinderDiameter: 1.0
sylinderDiameterColRatio: 1.0
# timestepping
dt: 0.001 # s
timeTotal: 0.01 # s
timeSnap: 0.001 # s
# ConstraintSolver
usePotential: false
conResTol: 0.00001 # 1e-5 format may be incompatible
conMaxIte: 100000
conSolverChoice: 0 # 0 for BBPGD, 1 for APGD, etc
